Fix non existing command in script

diff --git a/src/main/scripts/push-to-cloud-foundry b/src/main/scripts/push-to-cloud-foundry
--- a/src/main/scripts/push-to-cloud-foundry
+++ b/src/main/scripts/push-to-cloud-foundry
@@ -26,7 +26,8 @@ check_dependencies() {
   do
     if ! command -v "$bin" > /dev/null
     then
-      fail "$bin required, but not found in PATH."
+      echo "$bin required, but not found in PATH."
+      exit 1
     fi
   done
 }
